import type { IndustryBlueprint } from './types'

export const INDUSTRY_BLUEPRINTS: Record<IndustryBlueprint['id'], IndustryBlueprint> = {
  carwash: {
    id: 'carwash',
    label: 'Car Wash',
    vertical: 'carwash',
    operatorLabel: 'Site operator',
    servicePointLabel: 'Bay',
    servicePointPlural: 'Bays',
    servicePointExamples: ['Bay 1', 'Bay 2', 'Vacuum Station'],
    machineProviderOptions: ['unipay', 'custom'],
    paymentProviderOptions: ['stripe'],
    requiresMachineProvider: true,
    requiresQrCodes: true,
    setupChecklist: ['Brand profile complete', 'Stripe connected', 'Provider connected', 'Bays mapped', 'Webhook configured', 'Test payment verified'],
  },
  ev: {
    id: 'ev',
    label: 'EV Charging',
    vertical: 'auto',
    operatorLabel: 'Charge point operator',
    servicePointLabel: 'Charger',
    servicePointPlural: 'Chargers',
    servicePointExamples: ['Charger A1', 'Charger A2', 'Rapid Bay 3'],
    machineProviderOptions: ['custom', 'none'],
    paymentProviderOptions: ['stripe'],
    requiresMachineProvider: false,
    requiresQrCodes: true,
    setupChecklist: ['Operator profile complete', 'Stripe connected', 'Chargers mapped', 'QR links generated', 'Reporting enabled'],
  },
  laundry: {
    id: 'laundry',
    label: 'Laundry',
    vertical: 'takeaway',
    operatorLabel: 'Laundry operator',
    servicePointLabel: 'Machine',
    servicePointPlural: 'Machines',
    servicePointExamples: ['Washer 1', 'Dryer 2', 'Ironing Station'],
    machineProviderOptions: ['custom', 'none'],
    paymentProviderOptions: ['stripe'],
    requiresMachineProvider: false,
    requiresQrCodes: true,
    setupChecklist: ['Business profile complete', 'Stripe connected', 'Machines mapped', 'QR codes generated'],
  },
  dogwash: {
    id: 'dogwash',
    label: 'Dog Wash',
    vertical: 'grooming',
    operatorLabel: 'Dog wash operator',
    servicePointLabel: 'Wash station',
    servicePointPlural: 'Wash stations',
    servicePointExamples: ['Dog Wash 1', 'Dog Wash 2'],
    machineProviderOptions: ['custom', 'none'],
    paymentProviderOptions: ['stripe'],
    requiresMachineProvider: false,
    requiresQrCodes: true,
    setupChecklist: ['Business profile complete', 'Stripe connected', 'Stations mapped', 'QR codes generated'],
  },
  parking: {
    id: 'parking',
    label: 'Parking',
    vertical: 'restaurant',
    operatorLabel: 'Parking operator',
    servicePointLabel: 'Zone',
    servicePointPlural: 'Zones',
    servicePointExamples: ['Zone A', 'Upper Deck', 'Bay 12'],
    machineProviderOptions: ['custom', 'none'],
    paymentProviderOptions: ['stripe'],
    requiresMachineProvider: false,
    requiresQrCodes: true,
    setupChecklist: ['Operator profile complete', 'Stripe connected', 'Zones mapped', 'QR codes generated', 'Pricing rules confirmed'],
  },
}

export function getIndustryBlueprint(industry: IndustryBlueprint['id']) {
  return INDUSTRY_BLUEPRINTS[industry]
}
